import "../styles/main.scss";
import Criteria from "./filter-criteria";
import Filter from "./filter";
const apartments = [
  {
    id: 1,
    name: "Apartment A",
    price: 120000,
    kitchens: 1,
    bathrooms: 1,
    type: "Studio",
    area: 35,
    features: ["Balcony", "Parking"],
  },
  {
    id: 2,
    name: "Apartment B",
    price: 250000,
    kitchens: 1,
    bathrooms: 1,
    type: "Studio",
    area: 75,
    features: ["Garden", "Garage", "Balcony", "Parking"],
  },
  {
    id: 3,
    name: "Apartment C",
    price: 180000,
    kitchens: 1,
    bathrooms: 1,
    type: "House",
    area: 50,
    features: ["Balcony"],
  },
  {
    id: 4,
    name: "Apartment D",
    price: 300000,
    kitchens: 1,
    bathrooms: 2,
    type: "Three-bedroom",
    area: 90,
    features: ["Terrace", "Garage"],
  },
  {
    id: 5,
    name: "Apartment E",
    price: 100000,
    kitchens: 1,
    bathrooms: 1,
    type: "Studio",
    area: 30,
    features: ["Parking"],
  },
  {
    id: 6,
    name: "Apartment F",
    price: 220000,
    kitchens: 1,
    bathrooms: 2,
    type: "Apartment",
    area: 70,
    features: ["Garden"],
  },
  {
    id: 7,
    name: "Apartment G",
    price: 150000,
    kitchens: 1,
    bathrooms: 1,
    type: "House",
    area: 45,
    features: ["Balcony"],
  },
  {
    id: 8,
    name: "Apartment H",
    price: 280000,
    kitchens: 1,
    bathrooms: 2,
    type: "Three-bedroom",
    area: 85,
    features: ["Terrace", "Parking"],
  },
  {
    id: 9,
    name: "Apartment I",
    price: 130000,
    kitchens: 1,
    bathrooms: 1,
    type: "Studio",
    area: 40,
    features: ["Balcony"],
  },
  {
    id: 10,
    name: "Apartment J",
    price: 260000,
    kitchens: 1,
    bathrooms: 2,
    type: "Apartment",
    area: 80,
    features: ["Garage"],
  },
  {
    id: 11,
    name: "Apartment K",
    price: 170000,
    kitchens: 1,
    bathrooms: 1,
    type: "House",
    area: 55,
    features: ["Balcony", "Parking"],
  },
  {
    id: 12,
    name: "Apartment L",
    price: 310000,
    kitchens: 1,
    bathrooms: 2,
    type: "Three-bedroom",
    area: 95,
    features: ["Terrace", "Garden"],
  },
  {
    id: 13,
    name: "Apartment M",
    price: 110000,
    kitchens: 1,
    bathrooms: 1,
    type: "Studio",
    area: 32,
    features: ["Parking"],
  },
  {
    id: 14,
    name: "Apartment N",
    price: 240000,
    kitchens: 1,
    bathrooms: 2,
    type: "Apartment",
    area: 72,
    features: ["Garage"],
  },
  {
    id: 15,
    name: "Apartment O",
    price: 160000,
    kitchens: 1,
    bathrooms: 1,
    type: "House",
    area: 48,
    features: ["Balcony"],
  },
  {
    id: 16,
    name: "Apartment P",
    price: 290000,
    kitchens: 1,
    bathrooms: 2,
    type: "Three-bedroom",
    area: 88,
    features: ["Terrace", "Parking"],
  },
  {
    id: 17,
    name: "Apartment Q",
    price: 140000,
    kitchens: 1,
    bathrooms: 1,
    type: "Studio",
    area: 38,
    features: ["Balcony"],
  },
  {
    id: 18,
    name: "Apartment R",
    price: 270000,
    kitchens: 1,
    bathrooms: 2,
    type: "Apartment",
    area: 78,
    features: ["Garden"],
  },
  {
    id: 19,
    name: "Apartment S",
    price: 190000,
    kitchens: 1,
    bathrooms: 1,
    type: "House",
    area: 52,
    features: ["Balcony", "Parking"],
  },
  {
    id: 20,
    name: "Apartment T",
    price: 320000,
    kitchens: 2,
    bathrooms: 2,
    type: "Three-bedroom",
    area: 100,
    features: ["Terrace", "Garage"],
  },
];

document.addEventListener("DOMContentLoaded", () => {
  const criteria = new Criteria();
  const filter = new Filter(apartments);

  const filterButton = document.getElementById("filter") as HTMLButtonElement;
  filterButton?.addEventListener("click", () => {
    filter.applyFilters(criteria.get());
  });
});
